### ISSUE TITLE
Grinder Crafting Broken

### ISSUE THREAD

**Issue by Min-vi** [vautheman/coffeecraft#2]
The grinder is unable to be crafted as it calls for "empty tag minecraft:slabs"

**Comment by Min-vi** [comment]
Attaching images to show what I mean.
![Screenshot 2024-11-20 013546](https://github.com/user-attachments/assets/26804867-58de-4d4f-b8e7-c7f7057fed85)
![Screenshot 2024-11-20 013541](https://github.com/user-attachments/assets/e93820db-b1e8-45d7-8317-ebde8be05391)

**Comment by ProjectHSI** [comment]
do you have other mods installed?

**Comment by Min-vi** [comment]
Yes

**Comment by Min-vi** [comment]
Okay, I did another test and it does seem to be due to some kind of incompatibility. Will test to see which mod is conflicting and report back.

**Comment by Min-vi** [comment]
Alright, it's apparently due to some kind of incompatibility with the mod [Etcetera](https://www.curseforge.com/minecraft/mc-mods/etcetera)

**Comment by ProjectHSI** [comment]
Install LMFT (Load my F***ing Tags)

https://www.curseforge.com/minecraft/mc-mods/lmft

**Comment by Min-vi** [comment]
That fixed it, thanks.
